### Make Application
POST http://localhost:3000/applications
Content-Type: application/json

{
    "company": "Astra Indonesia",
    "position": "Frontend Developer",
    "status": "applied"
}

### Get All Application
GET http://localhost:3000/applications

### Get Application by Position
GET http://localhost:3000/applications?position=front

### Get Application by ID
GET http://localhost:3000/applications?id=df5c8b0e-9dc7-4852-afce-c12b14f3c8f0

### Update Status of an Application
PUT http://localhost:3000/applications/333
Content-Type: application/json

{
    "status": "applied"
}

### Delete Application
DELETE http://localhost:3000/applications/f2a33931-9a90-404b-b12a-05a5f104a608